### ISSUE TITLE
error: redefinition of ‘template<class T> v8::Local<T>

### ISSUE THREAD

**Issue by binarykitchen** [nodejs/nan#420]
due to a nan error i fail to compile the sharp library:

```
$ npm i                                                                                                                               1   staging 
/
> sharp@0.11.1 install /home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/sharp
> node-gyp rebuild

make: Entering directory '/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/sharp/build'
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
In file included from ../src/metadata.cc:4:0:
../node_modules/nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:319:17: note: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^
../node_modules/nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^
../node_modules/nan/nan.h:334:27: note: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:768:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:768:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/metadata.cc:4:
/home/michael-heuberger/.node-gyp/3.1.0/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Handle<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/michael-heuberger/.node-gyp/3.1.0/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/michael-heuberger/.node-gyp/3.1.0/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/michael-heuberger/.node-gyp/3.1.0/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/metadata.cc:4:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:772:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
../node_modules/nan/nan.h:780:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
sharp.target.mk:105: recipe for target 'Release/obj.target/sharp/src/metadata.o' failed
make: *** [Release/obj.target/sharp/src/metadata.o] Error 1
make: Leaving directory '/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-26-generic
gyp ERR! command "/usr/bin/iojs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/sharp
gyp ERR! node -v v3.1.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 3.19.0-26-generic
npm ERR! argv "/usr/bin/iojs" "/usr/bin/npm" "i"
npm ERR! node v3.1.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
```

**Comment by rvagg** [comment]
unfortunately this is a problem with the sharp library, they need to upgrade to nan >= 2.0.0 to get io.js v3.x support, you should encourage them to get on this to be ready for Node v4. https://github.com/lovell/sharp/blob/045680fba59750edd0ff366ab45bb0c97965e152/package.json#L50

Use https://gist.github.com/thlorenz/7e9d8ad15566c99fd116 to kickstart the upgrade process for all the changes required for nan@2.

**Comment by binarykitchen** [comment]
thanks man, will let them know

**Comment by lovell** [comment]
@binarykitchen You'll be pleased to hear the work to migrate sharp to io.js v3 via nan v2 started a couple of weeks ago and this task is being tracked at https://github.com/lovell/sharp/issues/246

Thank you @rvagg and co for all the time you continue to spend working on nan. A couple of hours yesterday learning about the new V8 MaybeLocal-based APIs provided me with only a fraction of the pain you must have been through trying to wrap it.

**Comment by kkoopa** [comment]
Wrapping the Maybe API was actually quite straightforward and less of a headache than many other changes.
It's fairly well contained in two files https://github.com/nodejs/nan/blob/master/nan_maybe_43_inl.h
https://github.com/nodejs/nan/blob/master/nan_maybe_pre_43_inl.h, where the former just forwards methods directly to V8, while the latter is the actual backport of the maybe classes which all results are wrapped with.

**Comment by lovell** [comment]
Thanks for the info @kkoopa, I might have to add macros to make my code look more like Haskell ;)

**Comment by binarykitchen** [comment]
@rvagg @lovell I have similar problems again with other packages: timekit@1.0.3 and v8tools@0.2.2

both node-gyp rebuilds fail with similar errors. using node v4.2.4 here. here one error out of many more:

```
> timekit@1.0.3 install /var/www/xxx/source/node_modules/timekit
> node-gyp rebuild

make: Entering directory `/var/www/xxx/source/node_modules/timekit/build'
  CXX(target) Release/obj.target/timekit/src/timekit_posix.o
../src/timekit_posix.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Time(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/timekit_posix.cc:37:12: error: ‘NanScope’ was not declared in this scope
   NanScope();
```

both packages are not maintained anymore but required in many other packages.

what should i do here? any recommendations?

**Comment by rvagg** [comment]
Not much you can do except try and get a PR in or simply fork and publish as something else and then encourage dependents to upgrade

**Comment by binarykitchen** [comment]
thanks man. PRs are out of question because their git repositories are gone:
404 https://github.com/dmelikyan/node-timekit
404 https://github.com/nodetime/node-v8tools

looks like i ll have to do it the painful way :(

**Comment by binarykitchen** [comment]
nodetime is using node-timekit and its github repo is also gone, grrrr. and nodetime is being used in look which hasn't been updated for 3 yrs.

in my project, i see no node module using the look package. but why is npm installing it? weird ... is there a trick to find out which package is using look with an npm command?

**Comment by rvagg** [comment]
`npm ls` maybe, or look at `npm shrinkwrap` output, although npm v3 has kind of changed all of that so it's probably even less useful than it used to be. You could just grep all of the package.json files in your node_modules directory to find out who's using it and work backward from there.
