### ISSUE TITLE
unable to run tests

### ISSUE THREAD

**Issue by andrewrk** [nodejs/nan#439]
```
$ npm run-script rebuild-tests

> nan@2.0.8 rebuild-tests /home/andy/Downloads/nan
> pangyp rebuild --msvs_version=2013 --directory test

gyp: /home/andy/.node-gyp/3.0.0/common.gypi not found (cwd: /home/andy/Downloads/nan/test) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/andy/Downloads/nan/node_modules/pangyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.6
gyp ERR! command "/nix/store/35kyxj6n6xybb83m882q5kdijlf7isps-iojs-3.0.0/bin/iojs" "/home/andy/Downloads/nan/node_modules/.bin/pangyp" "rebuild" "--msvs_version=2013" "--directory" "test"
gyp ERR! cwd /home/andy/Downloads/nan/test
gyp ERR! node -v v3.0.0
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok 

npm ERR! Linux 4.1.6
npm ERR! argv "/nix/store/35kyxj6n6xybb83m882q5kdijlf7isps-iojs-3.0.0/bin/iojs" "/nix/store/35kyxj6n6xybb83m882q5kdijlf7isps-iojs-3.0.0/bin/npm" "run-script" "rebuild-tests"
npm ERR! node v3.0.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
npm ERR! nan@2.0.8 rebuild-tests: `pangyp rebuild --msvs_version=2013 --directory test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nan@2.0.8 rebuild-tests script 'pangyp rebuild --msvs_version=2013 --directory test'.
npm ERR! This is most likely a problem with the nan package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     pangyp rebuild --msvs_version=2013 --directory test
npm ERR! You can get their info via:
npm ERR!     npm owner ls nan
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/andy/Downloads/nan/npm-debug.log
```

btw aren't you glad I pasted this output and did not heed the instructions:

```
npm ERR! Please include the following file with any support request:
npm ERR!     /home/andy/Downloads/nan/npm-debug.log
```

boy sure would be nice if npm [did not do that](https://github.com/npm/npm/issues/9347).

**Comment by kkoopa** [comment]
Something is wrong with your node environment or installation, since it complains about
> /home/andy/.node-gyp/3.0.0/common.gypi not found

The tests run just fine. https://travis-ci.org/nodejs/nan/jobs/77640890

**Comment by andrewrk** [comment]
I don't see why I should have to have ~/.node-gyp/3.0.0/common.gypi on my computer. I don't need to customize gyp and it's silly to have the user create that file if they don't need it.

**Comment by kkoopa** [comment]
Because that's where node-gyp has downloaded io.js 3.0.0 and is searching for it. You're not supposed to create it, you're supposed to have it. Your environment is faulty.

**Comment by rvagg** [comment]
`rm -rf ~/.node-gyp` and start again, be patient when it first runs as it needs to download the source file
