### ISSUE TITLE
(Windows) How to build nodejs nan based addons with node.exe build from source code?

### ISSUE THREAD

**Issue by 3foil** [nodejs/nan#472]
Hi,  
I built my own debug version of node.exe from the source code and tried to build an addon based on nan, but unsuccessfully. 

Adding my node.exe into PATH env variable doesn't work because node-gyp doesn't like "pre" versions of node.exe and recommends to use --nodedir flag instead :
```
C:\REPO\node.js\nan\examples\async_pi_estimate>node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@4.1.2-pre | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
```

**So I tried the approach with the --nodedir flag  - here are my steps:**

1) install nodejs from [here](https://nodejs.org/dist/v4.1.1/node-v4.1.1-x64.msi)
2) install node-gyp
```
npm install -g node-gyp
```

3) Build a debug version of node.exe
```
C:\REPO\node.js\>git clone https://github.com/nodejs/node
C:\REPO\node.js>cd node
C:\REPO\node.js\node>vcbuild.bat debug nosign x64
```
4) Clone your repo to get the example
```
C:\REPO\node.js>git clone https://github.com/nodejs/nan
C:\REPO\node.js>cd nan\examples\async_pi_estimate
C:\REPO\node.js\nan\examples\async_pi_estimate>
```
5) install nan
```
C:\REPO\node.js\nan\examples\async_pi_estimate>npm install --save nan
```
6) Configure the addon using path to my debug version of node.exe with --nodedir switch:
```
C:\REPO\node.js\nan\examples\async_pi_estimate>node-gyp configure --nodedir="c:\REPO\node.js\node\Debug"
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@4.1.1 | win32 | x64
gyp info spawn C:\Programs\Python2.7.10\python.exe
gyp info spawn args [ 'C:\\Users\\trifoil\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\REPO\\node.js\\nan\\examples\\async_pi_estimate\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\trefoil\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'c:\\REPO\\node.js\\node\\Debug\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=c:\\REPO\\node.js\\node\\Debug',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\trefoil\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\REPO\\node.js\\nan\\examples\\async_pi_estimate',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\REPO\\node.js\\nan\\examples\\async_pi_estimate\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
```
7) Build the addon:
```
C:\REPO\node.js\nan\examples\async_pi_estimate>node-gyp build --debug
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@4.1.1 | win32 | x64
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Debug;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  addon.cc
C:\REPO\node.js\nan\examples\async_pi_estimate\node_modules\nan\nan.h(23): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory [C:\REPO\node.js\nan\examples\async_
pi_estimate\build\addon.vcxproj]
  pi_est.cc
  sync.cc
C:\REPO\node.js\nan\examples\async_pi_estimate\node_modules\nan\nan.h(23): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory [C:\REPO\node.js\nan\examples\async_
pi_estimate\build\addon.vcxproj]
  async.cc
C:\REPO\node.js\nan\examples\async_pi_estimate\node_modules\nan\nan.h(23): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory [C:\REPO\node.js\nan\examples\async_
pi_estimate\build\addon.vcxproj]
  Generating Code...
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\trefiol\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "c:\\Programs\\nodejs\\node.exe" "C:\\Users\\trefiol\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--debug"
gyp ERR! cwd C:\REPO\node.js\nan\examples\async_pi_estimate
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```
Multiple "fatal error C1083: Cannot open include file: 'uv.h" followed.

So, my question here - what did I miss? 

Thanks!

**Comment by TooTallNate** [comment]
You're very close here. You need to specify `--nodedir="c:\REPO\node.js\node"` (i.e. drop the "Debug" part). The nodedir is the root directory of the node repo/tarball.

**Comment by 3foil** [comment]
Thanks a lot. It works!
