### ISSUE TITLE
0.10.38  Error: Symbol uname2_module not found.

### ISSUE THREAD

**Issue by i5ting** [nodejs/nan#520]
```
 openf .

/Users/sang/.nvm/v0.10.38/lib/node_modules/openf/node_modules/uname2/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Symbol uname2_module not found.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/Users/sang/.nvm/v0.10.38/lib/node_modules/openf/node_modules/uname2/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/sang/.nvm/v0.10.38/lib/node_modules/openf/node_modules/uname2/index.js:1:104)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

it can work at 4.2 but not 0.10.38,  is nan not work on 0.10?

**Comment by i5ting** [comment]
uname2 is a simple nodejs addon, see https://github.com/i5ting/uname2

**Comment by agnat** [comment]
NAN works fine with 0.10. Check your `NODE_MODULE(...)` call. Make sure the module name is the same as the `target_name` in the gyp file.

**Comment by i5ting** [comment]
thanks @agnat
