### ISSUE TITLE
fatal error C1060: compiler is out of heap space

### ISSUE THREAD

**Issue by yunnysunny** [nodejs/nan#639]
I cloned the code from [node-addon-examples](https://github.com/nodejs/node-addon-examples) , then entered the directory of `1_hello_world/nan` to build it. But an error came up `nan.h(72): fatal error C1060: compiler is out of heap space`.

```
{lamb} node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.2 | win32 | x64
gyp info spawn D:\Python27\python.EXE
gyp info spawn args [ 'd:\\Users\\sunny\\AppData\\Roaming\\nvm\\v6.9.2\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'F:\\temp\\node-addon-examples\\1_hello_world\\nan\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'd:\\Users\\sunny\\AppData\\Roaming\\nvm\\v6.9.2\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\sunny\\.node-gyp\\6.9.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\sunny\\.node-gyp\\6.9.2',
gyp info spawn args   '-Dnode_gyp_dir=d:\\Users\\sunny\\AppData\\Roaming\\nvm\\v6.9.2\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=F:\\temp\\node-addon-examples\\1_hello_world\\nan',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'F:\\temp\\node-addon-examples\\1_hello_world\\nan\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  hello.cc
  win_delay_load_hook.cc
F:\temp\node-addon-examples\1_hello_world\nan\node_modules\.2.5.0@nan\nan.h(72): fatal error C1060: compiler is out of heap space (..\hello.cc) [F:\temp\node-addon-exa mples\1_hello_world\nan\build\hello.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (d:\Users\sunny\AppData\Roaming\nvm\v6.9.2\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "d:\\Program Files\\nodejs\\node.exe" "d:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\temp\node-addon-examples\1_hello_world\nan
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

The source code is [here](https://github.com/nodejs/node-addon-examples/blob/master/1_hello_world/nan/hello.cc) . I use vs 2012.

**Comment by bnoordhuis** [comment]
You need VS 2015 when building against node v6.x, VS 2012 won't cut it.  HTH.

**Comment by yunnysunny** [comment]
Can I use [visual c++ build tool](http://landinghub.visualstudio.com/visual-cpp-build-tools)? VS2015 is too large.

**Comment by bnoordhuis** [comment]
Build Tools is acceptable too, yes.

**Comment by yunnysunny** [comment]
I think the document should indicate that we need use vs2015(or vc build tool 2015) in Windows. I have confused by this problem almost half a day of time.

**Comment by Evil-Spirit** [comment]
I just leave it here https://twitter.com/Evl_Spirit/status/993777818294276096
