### ISSUE TITLE
Segmentation fault errno 139

### ISSUE THREAD

**Issue by Foxhunt** [nodejs/nan#727]
Hi,

running into a 139 error when using nan. 

Not sure if this is a problem with nan or with nodegit.

In our app nodegit is the only module that has a dependency on nan.
The app is running in a docker container based on the Dockerfile in  https://github.com/artcom/git-json-api.

npm start logs:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.0.3
3 info using node@v8.1.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle git-json-api@0.1.0~prestart: git-json-api@0.1.0
6 silly lifecycle git-json-api@0.1.0~prestart: no script for prestart, continuing
7 info lifecycle git-json-api@0.1.0~start: git-json-api@0.1.0
8 verbose lifecycle git-json-api@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle git-json-api@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle git-json-api@0.1.0~start: CWD: /app
11 silly lifecycle git-json-api@0.1.0~start: Args: [ '-c', 'node src/main.js' ]
12 silly lifecycle git-json-api@0.1.0~start: Returned: code: 139  signal: null
13 info lifecycle git-json-api@0.1.0~start: Failed to exec start script
14 verbose stack Error: git-json-api@0.1.0 start: `node src/main.js`
14 verbose stack Exit status 139
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:897:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid git-json-api@0.1.0
16 verbose cwd /app
17 verbose Linux 4.9.60-linuxkit-aufs
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 verbose node v8.1.3
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 139
23 error git-json-api@0.1.0 start: `node src/main.js`
23 error Exit status 139
24 error Failed at the git-json-api@0.1.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 139, true ]
```
Running `node src/main.js` instead of `npm start` shows:

``` bash
node: ../node_modules/nan/nan_object_wrap.h:33: static T *Nan::ObjectWrap::Unwrap(v8::Local<v8::Object>) [T = GitOid]: Assertion `object->InternalFieldCount() > 0' failed.
```

**Comment by bnoordhuis** [comment]
Can you report this to nodegit?  Thanks.

**Comment by Foxhunt** [comment]
ok
