### ISSUE TITLE
building node-sass with node v10 failed on nan's error

### ISSUE THREAD

**Issue by Mactaivsh** [nodejs/nan#767]
I just upgrade  my node version to v10.0.0

and reinstall the packages of one of my projects, using `yarn install`

then a error occurred

I switched back to v8.11.1(LTS) and try to reinstall again, everything seems ok.

from yarn-error.log:

```
  In file included from ../src/binding.cpp:1:
  In file included from ../../nan/nan.h:190:
  ../../nan/nan_maybe_43_inl.h:112:15: **error: no member named 'ForceSet' in 'v8::Object'**
    return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
           ~~~  ^
  In file included from ../src/binding.cpp:1:
  ../../nan/nan.h:832:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
      return node::MakeCallback(
                   ^
  /Users/maczhanchao/.node-gyp/10.0.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
  NODE_DEPRECATED("Use MakeCallback(..., async_context)",
  ^
  /Users/maczhanchao/.node-gyp/10.0.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
      __attribute__((deprecated(message))) declarator
                     ^
  In file included from ../src/binding.cpp:1:
  ../../nan/nan.h:847:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
      return node::MakeCallback(
                   ^
  /Users/maczhanchao/.node-gyp/10.0.0/include/node/node.h:164:1: note: 'MakeCallback' has been explicitly marked deprecated here
  NODE_DEPRECATED("Use MakeCallback(..., async_context)",
  ^
  /Users/maczhanchao/.node-gyp/10.0.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
      __attribute__((deprecated(message))) declarator
                     ^
  In file included from ../src/binding.cpp:1:
  ../../nan/nan.h:862:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
      return node::MakeCallback(
                   ^
  /Users/maczhanchao/.node-gyp/10.0.0/include/node/node.h:157:1: note: 'MakeCallback' has been explicitly marked deprecated here
  NODE_DEPRECATED("Use MakeCallback(..., async_context)",
  ^
  /Users/maczhanchao/.node-gyp/10.0.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
      __attribute__((deprecated(message))) declarator
                     ^
  In file included from ../src/binding.cpp:1:
  ../../nan/nan.h:1471:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
      return scope.Escape(node::MakeCallback(
                                ^
  /Users/maczhanchao/.node-gyp/10.0.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
  NODE_DEPRECATED("Use MakeCallback(..., async_context)",
  ^
  /Users/maczhanchao/.node-gyp/10.0.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
      __attribute__((deprecated(message))) declarator
                     ^
  4 warnings and 1 error generated.
  make: *** [Release/obj.target/binding/src/binding.o] Error 1
  gyp ERR! build error 
  gyp ERR! stack Error: `make` failed with exit code: 2
  gyp ERR! stack     at ChildProcess.onExit (/Users/maczhanchao/WorkSpace/as/node_modules/node-gyp/lib/build.js:276:23)
  gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
  gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
  gyp ERR! System Darwin 17.5.0
  gyp ERR! command "/Users/maczhanchao/.nvm/versions/node/v10.0.0/bin/node" "/Users/maczhanchao/WorkSpace/as/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
  gyp ERR! cwd /Users/maczhanchao/WorkSpace/as/node_modules/gulp-sass/node_modules/node-sass
  gyp ERR! node -v v10.0.0
  gyp ERR! node-gyp -v v3.5.0
  gyp ERR! not ok 
  Build failed with error code: 1
      at ProcessTermError.MessageError (/usr/local/Cellar/yarn/1.5.1_1/libexec/lib/cli.js:186:110)
      at new ProcessTermError (/usr/local/Cellar/yarn/1.5.1_1/libexec/lib/cli.js:226:113)
      at ChildProcess.<anonymous> (/usr/local/Cellar/yarn/1.5.1_1/libexec/lib/cli.js:30281:17)
      at ChildProcess.emit (events.js:182:13)
      at maybeClose (internal/child_process.js:947:16)
      at Socket.stream.socket.on (internal/child_process.js:368:11)
      at Socket.emit (events.js:182:13)
      at Pipe._handle.close [as _onclose] (net.js:598:12)
```

**Comment by bnoordhuis** [comment]
Can you report that to node-sass?
