### ISSUE TITLE
Build broken on node 2.9.0

### ISSUE THREAD

**Issue by FFY00** [nodejs/nan#802]
```
../node_modules/nan/nan.h:559:9: error: ‘async_context’ in namespace ‘node’ does not name a type
   node::async_context context;
         ^~~~~~~~~~~~~
../node_modules/nan/nan.h: In constructor ‘Nan::AsyncResource::AsyncResource(v8::Local<v8::String>, v8::Local<v8::Object>)’:
../node_modules/nan/nan.h:490:5: error: ‘context’ was not declared in this scope
     context = node::EmitAsyncInit(isolate, resource, name);
     ^~~~~~~
../node_modules/nan/nan.h:490:5: note: suggested alternative: ‘connect’
     context = node::EmitAsyncInit(isolate, resource, name);
     ^~~~~~~
     connect
../node_modules/nan/nan.h:490:21: error: ‘EmitAsyncInit’ is not a member of ‘node’
     context = node::EmitAsyncInit(isolate, resource, name);
                     ^~~~~~~~~~~~~
../node_modules/nan/nan.h: In constructor ‘Nan::AsyncResource::AsyncResource(const char*, v8::Local<v8::Object>)’:
../node_modules/nan/nan.h:506:5: error: ‘context’ was not declared in this scope
     context = node::EmitAsyncInit(isolate, resource, name_string);
     ^~~~~~~
../node_modules/nan/nan.h:506:5: note: suggested alternative: ‘connect’
     context = node::EmitAsyncInit(isolate, resource, name_string);
     ^~~~~~~
     connect
../node_modules/nan/nan.h:506:21: error: ‘EmitAsyncInit’ is not a member of ‘node’
     context = node::EmitAsyncInit(isolate, resource, name_string);
                     ^~~~~~~~~~~~~
../node_modules/nan/nan.h: In destructor ‘Nan::AsyncResource::~AsyncResource()’:
../node_modules/nan/nan.h:513:11: error: ‘EmitAsyncDestroy’ is not a member of ‘node’
     node::EmitAsyncDestroy(isolate, context);
           ^~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:513:37: error: ‘context’ was not declared in this scope
     node::EmitAsyncDestroy(isolate, context);
                                     ^~~~~~~
../node_modules/nan/nan.h:513:37: note: suggested alternative: ‘connect’
     node::EmitAsyncDestroy(isolate, context);
                                     ^~~~~~~
                                     connect
../node_modules/nan/nan.h: In member function ‘Nan::MaybeLocal<v8::Value> Nan::AsyncResource::runInAsyncScope(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:526:62: error: ‘context’ was not declared in this scope
         v8::Isolate::GetCurrent(), target, func, argc, argv, context);
                                                              ^~~~~~~
../node_modules/nan/nan.h:526:62: note: suggested alternative: ‘connect’
         v8::Isolate::GetCurrent(), target, func, argc, argv, context);
                                                              ^~~~~~~
                                                              connect
../node_modules/nan/nan.h: In member function ‘Nan::MaybeLocal<v8::Value> Nan::AsyncResource::runInAsyncScope(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:539:64: error: ‘context’ was not declared in this scope
         v8::Isolate::GetCurrent(), target, symbol, argc, argv, context);
                                                                ^~~~~~~
../node_modules/nan/nan.h:539:64: note: suggested alternative: ‘connect’
         v8::Isolate::GetCurrent(), target, symbol, argc, argv, context);
                                                                ^~~~~~~
                                                                connect
../node_modules/nan/nan.h: In member function ‘Nan::MaybeLocal<v8::Value> Nan::AsyncResource::runInAsyncScope(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:552:64: error: ‘context’ was not declared in this scope
         v8::Isolate::GetCurrent(), target, method, argc, argv, context);
                                                                ^~~~~~~
../node_modules/nan/nan.h:552:64: note: suggested alternative: ‘connect’
         v8::Isolate::GetCurrent(), target, method, argc, argv, context);
                                                                ^~~~~~~
                                                                connect
../node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../node_modules/nan/nan.h:2167:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
```

**Comment by FFY00** [comment]
Let me double check this issue again.

**Comment by FFY00** [comment]
Seems right but it's not the build that is broken, it's the API?.

**Comment by FFY00** [comment]
Ran with npm (instead of yarn) and it seems there's an error associated with it.

**Comment by fivdi** [comment]
What would you like to achieve and what commands did you run to (try to) achieve this?

**Comment by FFY00** [comment]
This is related with https://github.com/brave/browser-laptop/issues/14883.

Yarn wasn't showing the relevant error message.

```
Error: Could not detect abi for version 8.0.7 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at getAbi (/home/anubis/git/pkg/brave/src/browser-laptop-0.23.79dev/node_modules/node-abi/index.js:30:9)
    at module.exports (/home/anubis/git/pkg/brave/src/browser-laptop-0.23.79dev/node_modules/prebuild-install/rc.js:65:12)
    at Object.<anonymous> (/home/anubis/git/pkg/brave/src/browser-laptop-0.23.79dev/node_modules/prebuild-install/bin.js:8:25)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
```

Guess this is not an nan issue. Sorry for for the mess.
