### ISSUE TITLE
Getting segmentation fault after receiving some callbacks from NAN layer

### ISSUE THREAD

**Issue by jay11ca39** [nodejs/nan#809]
Hello All,

I have written a native addon [Using NAN] for my cpp [pub-sub] library.
   - Subscriber that is receving the events from the publisher.
   - Calling the application callback.

So, my native addon is providing wrapper APIs for cpp library.
  - Js application will create subscriber object and will subscribe for event. Internally I am creating c++ subscriber, subscribe to it and will register addon callback to cpp layer.
  - I am using libuv for getting the asyn callback from c++ layer to addon layer, and then I am calling NAN callback for calling js callback.

For callback implementation in addon, I followed: https://github.com/nodejs/help/issues/1171

**Issue:**
After receving some events on subscriber side, subscriber sample is crashing [Segmentation fault].

**Crash logs:** 
```
(gdb) bt
#0  0x0000000000f87c74 in v8::internal::JSReceiver::GetCreationContext() ()
#1  0x0000000000afd25c in v8::Object::CreationContext() ()
#2  0x0000000001225044 in node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*) ()
#3  0x00007ffff47a539b in npubsub::NSubscriber::uvAsynCallback(uv_async_s*) ()
   from /home/jack/pubsubrepo/build/Release/pubsub.node
#4  0x000000000143e44b in uv__async_io (loop=0x21d0500 <default_loop_struct>, w=<optimized out>, events=<optimized out>) at ../deps/uv/src/unix/async.c:118
#5  0x000000000144ffa8 in uv__io_poll (loop=loop@entry=0x21d0500 <default_loop_struct>, timeout=-1) at ../deps/uv/src/unix/linux-core.c:400
#6  0x000000000143edd6 in uv_run (loop=0x21d0500 <default_loop_struct>, mode=UV_RUN_DEFAULT) at ../deps/uv/src/unix/core.c:368
#7  0x000000000122c1bd in node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) ()
#8  0x0000000001224d03 in node::Start(int, char**) ()
#9  0x00007ffff6bd8f45 in __libc_start_main (main=0x8acef0 <main>, argc=8, argv=0x7fffffffe328, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fffffffe318) at libc-start.c:287
```

**Observation:**
There is a strange observation on my subscriber sample: 

1. If, I am creating my subscriber object in sample application like this: 

`   subscriber = new subscriber(ip, port); `
  
   **Result**: It is working fine. 

2. If, I am creating the subscriber  object like this
   
`   var subscriber = new subscriber(ip, port); `
   
   **Result**: It is crashing after receiving some events.

**Environment details:**
* **Node.js Version**: v8.11.1
* **OS**: Linux  [Ubuntu : 14.04]

I am struggling with this issue since quite long. Any help will be appreciated.

Thanks in advance.

**Comment by jay11ca39** [comment]
**Full backtrace:**

```
(gdb) bt full
#0  0x0000000000f87c74 in v8::internal::JSReceiver::GetCreationContext() ()
No symbol table info available.
#1  0x0000000000afd25c in v8::Object::CreationContext() ()
No symbol table info available.
#2  0x0000000001225044 in node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*) ()
No symbol table info available.
#3  0x00007ffff47a539b in npubsub::NSubscriber::uvAsynCallback(uv_async_s*) ()
   from /home/jack/pubsubrepo/build/Release/pubsub.node
No symbol table info available.
#4  0x000000000143e44b in uv__async_io (loop=0x21d0500 <default_loop_struct>, w=<optimized out>, events=<optimized out>) at ../deps/uv/src/unix/async.c:118
        buf = "\001\000\000\000\000\000\000\000\320L2\002\000\000\000\000\200R2\002\000\000\000\000R\311\377\000\000\000\000\000`M0\002\000\000\000\000\200R2\002\000\000\000\000\240\235\377\377\377\177\000\000\320L2\002\000\000\000\000@\235\377\377\377\177", '\000' <repeats 19 times>, "\236\377\377\377\177\000\000@\236\377\377\377\177\000\000й\377\377\377\177\000\000\320L2\002\000\000\000\000\200R2\002\000\000\000\000\340\236\377\377\377\177\000\000\246\261\000\001\000\000\000\000\000\000\000\000\377\177\000\000\200\267\377\377\377\177\000\000\222\031\000\000\000\000\000\000@\242\060\002\000\000\000\000\240\235\377\377\377\177\000\000\001\002\000\000\000\000\000\000\230\302#\002\000\000\000\000V"...
        r = <optimized out>
        queue = {0x7fffffff9cb0, 0x7fffffff9cb0}
        q = <optimized out>
        h = <optimized out>
        __PRETTY_FUNCTION__ = "uv__async_io"
#5  0x000000000144ffa8 in uv__io_poll (loop=loop@entry=0x21d0500 <default_loop_struct>, timeout=-1) at ../deps/uv/src/unix/linux-core.c:400
        no_epoll_pwait = 0
        no_epoll_wait = 0
        events = {{events = 1, data = 8}, {events = 4294934528, data = 140737488331263}, {events = 4294948736, data = 18446666901737209855}, {events = 32767,
            data = 2390}, {events = 2390, data = 18446666901737177088}, {events = 32767, data = 140737488331472}, {events = 11889213, data = 18446641338091831296},
          {events = 32767, data = 11892500}, {events = 36866864, data = 17795858891150458880}, {events = 1, data = 140737488331328}, {events = 15, data = 0}, {
            events = 0, data = 36866864}, {events = 15, data = 9903397704933834752}, {events = 32513, data = 36741696}, {events = 36885152,
            data = 158341975186079744}, {events = 0, data = 140737488339376}, {events = 5407, data = 18446675560391245824}, {events = 32767,
            data = 140737488331504}, {events = 11892961, data = 18446641887847645184}, {events = 97, data = 15}, {events = 15, data = 1141615017}, {events = 256,
            data = 0}, {events = 4294951936, data = 369367220223}, {events = 0, data = 140737488339376}, {events = 5407, data = 18446675560391245824}, {
            events = 32767, data = 140737488331520}, {events = 17073464, data = 18446642300164505600}, {events = 32767, data = 16764929}, {events = 4294943680,
            data = 17795858891150491647}, {events = 32767, data = 3072}, {events = 52, data = 2475849424085975040}, {events = 0, data = 128}, {events = 0,
            data = 18446678103011885057}, {events = 32767, data = 140737488340104}, {events = 4294951936, data = 18446678103011917823}, {events = 32767,
            data = 36962976}, {events = 4294943712, data = 72314622060822527}, {events = 0, data = 36925360}, {events = 52, data = 18446643124798226432}, {
            events = 32767, data = 2305814462}, {events = 23, data = 51063781010178048}, {events = 0, data = 140737488331824}, {events = 11892500,
            data = 158341975186079744}, {events = 0, data = 4331925016}, {events = 4294943712, data = 64424542207}, {events = 0, data = 0}, {events = 36866864,
            data = 64424509440}, {events = 0, data = 6600781758}, {events = 2390, data = 158420521547988992}, {events = 0, data = 36866864}, {events = 4294951344,
            data = 24502788456447}, {events = 0, data = 140737488339376}, {events = 4294943888, data = 51079878547636223}, {events = 0, data = 5407}, {events = 15,
            data = 64424509440}, {events = 1141615017, data = 1099511627776}, {events = 4294944016, data = 18446678103011917823}, {events = 32767, data = 86}, {
            events = 4294951344, data = 24502788456447}, {events = 0, data = 140737488339376}, {events = 4294943904, data = 73329969509466111}, {events = 0,
            data = 0}, {events = 36885152, data = 18446643880712470528}, {events = 32767, data = 11891769}, {events = 36963696, data = 18446677484536594432}, {
            events = 32767, data = 140737488339824}, {events = 3974, data = 18446644086870900736}, {events = 32767, data = 16722579}, {events = 4294951928,
            data = 18446677484536627199}, {events = 32767, data = 140737488339960}, {events = 4294951200, data = 18446644567907270655}, {events = 32767,
            data = 16837356}, {events = 23137, data = 833223622656}, {events = 6, data = 48}, {events = 96, data = 18446644705346191360}, {events = 32767,
            data = 446676598790}, {events = 3974, data = 18446646766930497415}, {events = 32767, data = 140737488339824}, {events = 36957728, data = 0}, {
            events = 0, data = 140737488332416}, {events = 4294944560, data = 72174086435930111}, {events = 0, data = 140733193388156}, {events = 16839629,
            data = 23201413332992}, {events = 0, data = 140737488339376}, {events = 4294952072, data = 4295000063}, {events = 5406, data = 140737488337360}, {
            events = 4143421280, data = 32767}, {events = 0, data = 36963128}, {events = 3974, data = 158755425917861888}, {events = 0, data = 140737488332288}, {
            events = 11892500, data = 158341975186079744}, {events = 0, data = 4294967424}, {events = 4294944288, data = 30064803839}, {events = 0, data = 0}, {
            events = 36866864, data = 30064771072}, {events = 0, data = 6420377038}, {events = 4294944480, data = 158420521548021759}, {events = 0,
            data = 36961512}, {events = 0, data = 158755288478908416}, {events = 0, data = 36960056}, {events = 36958664, data = 51078912179961856}, {events = 0,
            data = 140737488339824}, {events = 4294944640, data = 158648738930262015}, {events = 0, data = 140737488338528}, {events = 4294950512, data = 32767}, {
            events = 0, data = 1407396362846208}, {events = 4294951072, data = 45788646375423}, {events = 0, data = 11889213}, {events = 4294944592,
            data = 51077898567712767}, {events = 0, data = 36866864}, {events = 16764929, data = 18446646217174679553}, {events = 32767, data = 4}, {events = 0,
            data = 18446674941915955200}, {events = 32767, data = 0}, {events = 36963128, data = 18446654600950841344}, {events = 32767, data = 140737488339824}, {
            events = 4294944752, data = 72325655831805951}, {events = 0, data = 140737488332688}, {events = 17078425, data = 18446646973088923648}, {
            events = 32767, data = 17063905067009}, {events = 36866864, data = 18446678068652146688}, {events = 32767, data = 50}, {events = 35633992,
            data = 18446677484536594432}, {events = 32767, data = 140737488334496}, {events = 36938288, data = 18446671918258978816}, {events = 32767,
            data = 140737488338544}, {events = 4294951792, data = 18446647247966863359}, {events = 32767, data = 16733988}, {events = 4294951792,
            data = 18446674941915987967}, {events = 32767, data = 140737488339824}, {events = 4294951200, data = 18446677484536627199}, {events = 32767,
            data = 140737488338464}, {events = 4294944928, data = 72358095719792639}, {events = 0, data = 140737488332896}, {events = 4294951792,
            data = 18446678068652179455}, {events = 32767, data = 140733193392005}, {events = 4294945280, data = 158755494637371391}, {events = 0,
            data = 140737488332960}, {events = 16837060, data = 158420521547988992}, {events = 0, data = 36961352}, {events = 4294944880,
            data = 18446674392160174079}, {events = 32767, data = 140737488339696}, {events = 36961352, data = 18446648553636888576}, {events = 32767,
            data = 140737488339232}, {events = 4294945280, data = 17046725230591}, {events = 0, data = 140737488339232}, {events = 11889213,
            data = 18446648553636888576}, {events = 32767, data = 11892500}, {events = 36866864, data = 73402296758697984}, {events = 1, data = 140737488333008}, {
            events = 6, data = 0}, {events = 0, data = 36866864}, {events = 6, data = 15407675440407511040}, {events = 32513, data = 140737488333312}, {
            events = 36885152, data = 158341975186079744}, {events = 0, data = 140737488339248}, {events = 3355, data = 18446675010635431936}, {events = 32767,
            data = 140737488333184}, {events = 11892961, data = 18446648897234272256}, {events = 32767, data = 6}, {events = 6, data = 3615702597}, {events = 256,
            data = 36866864}, {events = 4294951808, data = 369367220223}, {events = 0, data = 140737488339248}, {events = 3355, data = 18446675010635431936}, {
            events = 32767, data = 140737488333200}, {events = 17073464, data = 18446649515709562880}, {events = 32767, data = 16764929}, {events = 36866864,
            data = 18446675010635431936}, {events = 32767, data = 2875}, {events = 4294951216, data = 18446649653148549119}, {events = 32767, data = 11892961}, {
            events = 4294951072, data = 18446677553256103935}, {events = 32767, data = 140737488339976}, {events = 4294951808, data = 18446677553256103935}, {
            events = 32767, data = 11889213}, {events = 4294945408, data = 51077898567712767}, {events = 0, data = 36866864}, {events = 4294951216,
            data = 18446649721867993089}, {events = 32767, data = 12}, {events = 0, data = 158341975186079744}, {events = 0, data = 12}, {events = 832093222,
            data = 18446677553256103681}, {events = 32767, data = 36885152}, {events = 36866864, data = 18446675010635431936}, {events = 32767, data = 3391}, {
            events = 4294951216, data = 18446650477782269951}, {events = 32767, data = 11892961}, {events = 36866864, data = 51539607552}, {events = 0,
            data = 14259371923292028940}, {events = 0, data = 256}, {events = 0, data = 140737488339840}, {events = 86, data = 18446675010635431936}, {
            events = 32767, data = 3391}, {events = 4294951216, data = 18446650546501746687}, {events = 32767, data = 17073464}, {events = 4294945632,
            data = 72004821774794751}, {events = 0, data = 140737488333664}, {events = 11892961, data = 18446650752660144128}, {events = 32767, data = 7}...}
        pe = 0x7fffffffa1c0
        e = {events = 1, data = 8}
        real_timeout = -1
        q = <optimized out>
        w = <optimized out>
        sigset = {__val = {140737488336768, 0, 140737488331264, 16849474, 2, 140737488336448, 0, 6399, 36741696, 36812448, 140737488331216, 7, 0, 0, 0,
            140737336809392}}
        sigmask = 0
        base = 2082704301
        have_signals = <optimized out>
        nevents = 0
        count = 48
        nfds = 1
        fd = <optimized out>
        op = <optimized out>
        i = <optimized out>
        __PRETTY_FUNCTION__ = "uv__io_poll"
#6  0x000000000143edd6 in uv_run (loop=0x21d0500 <default_loop_struct>, mode=UV_RUN_DEFAULT) at ../deps/uv/src/unix/core.c:368
        timeout = <optimized out>
        r = 1
#7  0x000000000122c1bd in node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) ()
No symbol table info available.
#8  0x0000000001224d03 in node::Start(int, char**) ()
No symbol table info available.
#9  0x00007ffff6bd8f45 in __libc_start_main (main=0x8acef0 <main>, argc=8, argv=0x7fffffffe328, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fffffffe318) at libc-start.c:287
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 8750135525826613513, 9104920, 140737488347936, 0, 0, -8750135526510833399, -8750119565224980215},
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x15634d0 <__libc_csu_init>, 0x7fffffffe328}, data = {prev = 0x0, cleanup = 0x0,
              canceltype = 22426832}}}
        not_first_call = <optimized out>
#10 0x00000000008aee41 in _start ()
No symbol table info available.
```

**Comment by jay11ca39** [comment]
Hello @kkoopa ,
Can you please provide your opinion?
It will be a great help.

**Comment by jay11ca39** [comment]
Hello @kkoopa ,
Please let me know if any other information is needed. ?

**Comment by kkoopa** [comment]
Hi, I have not had much free time to look into this. Based on the stack trace, it seems like it would have something to do with accessing V8 from different threads. However, this does not explain why the observed behavior is not consistent.

**Comment by bnoordhuis** [comment]
@jay11ca39 Is this issue still relevant or can it be closed out?

**Comment by bnoordhuis** [comment]
No follow-up, closing.
